name: Sync Shopify to GitHub

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v3

      - name: Commit Shopify theme files
        run: |
          git config user.name "shopify[bot]"
          git config user.email "bot@shopify.com"
          git add .
          git commit -m "Sync from Shopify to GitHub" || echo "No changes"
          git push origin main
